#!/usr/bin/env bash

# Time-stamp: <2017-09-13 10:59:43 Wednesday by ahei>

# @file ps.sh
# @version 1.0
# @author ahei

readonly PROGRAM_NAME="rps"
readonly PROGRAM_VERSION="1.0.0"

home=`cd $(dirname "$0") && pwd`

version()
{
    echo "${PROGRAM_NAME} ${PROGRAM_VERSION}"
    exit 1
}

# echo to stderr
echoe()
{
    printf "$*\n" 1>&2
}

usage()
{
    local code=1
    local redirect
    
    if [ $# -gt 0 ]; then
        code="$1"
    fi

    if [ "$code" != 0 ]; then
        redirect="1>&2"
    fi

    eval cat "$redirect" << EOF
usage: ${PROGRAM_NAME} [OPTIONS] CLUSTER PATTERN [PS_OPTIONS]

Options:
    -o REMOTE_OPTIONS
        Set remote's options.
    -v  Output version info.
    -h  Output this help.
EOF

    exit "$code"
}

optInd=1

while getopts ":hvo:" OPT; do
    case "$OPT" in
        o)
            remoteOptions="$OPTARG"
            ;;

        v)
            version
            ;;

        h)
            usage 0
            ;;

        :)
            case "${OPTARG}" in
                ?)
                    echoe "Option \`-${OPTARG}' need argument.\n"
                    usage
            esac
            ;;

        ?)
            echoe "Invalid option \`-${OPTARG}'.\n"
            usage
            ;;
    esac
done

shift $((optInd - 1))

if [ $# -lt 2 ]; then
    usage
fi

cluster=$1
pattern=$2
shift 2

remote -q $remoteOptions "$cluster" "ps -ef $@ | fgrep '$pattern' | fgrep -v grep" | fgrep -v "$PROGRAM_NAME"
